#--------------------------------------------------------------------
# Cert-Manager values
#--------------------------------------------------------------------
# Tutorial on cert-manager in k8s https://youtu.be/hoLUigg4V18
cert-manager:
  namespace: security #Make sure this matches the value in the variables.tf file

#--------------------------------------------------------------------
# Ingress-Nginx values
#--------------------------------------------------------------------
ingress-nginx:
  namespaceOverride: "ingress-nginx" #Make sure this matches the value in the variables.tf file



#--------------------------------------------------------------------
# Global values
#--------------------------------------------------------------------
tls:
  apiSecret: ecommerce-api-tls
  uiSecret: ecommerce-ui-tls

secrets:
  secretName: ecommerce-secrets
  keys:
    EcommerceJwtSettingsKey: EcommerceJwtSettingsKey
    EcommercePaypalClientId: EcommercePaypalClientId
    EcommercePaypalSecret: EcommercePaypalSecret
    EcommerceRabbitMQUri: EcommerceRabbitMQUri
    EcommerceRabbitMQUsername: EcommerceRabbitMQUsername
    EcommerceRabbitMQPassword: EcommerceRabbitMQPassword
    EcommerceMailSettingsHost: EcommerceMailSettingsHost
    EcommerceMailSettingsPort: EcommerceMailSettingsPort
    EcommerceMailSettingsUserName: EcommerceMailSettingsUserName
    EcommerceMailSettingsPassword: EcommerceMailSettingsPassword
  values:
    EcommerceJwtSettingsKey: ""
    EcommercePaypalClientId: ""
    EcommercePaypalSecret: ""
    EcommerceRabbitMQUri: ""
    EcommerceRabbitMQUsername: ""
    EcommerceRabbitMQPassword: ""
    EcommerceMailSettingsHost: ""
    EcommerceMailSettingsPort: ""
    EcommerceMailSettingsUserName: ""
    EcommerceMailSettingsPassword: ""

# IF you change these values
# MAKE SURE they match what is put in the kubernetes.tf file
connectionString:
  secretName: "ecommerce-database"
  secretKey: "connection-string"


#--------------------------------------------------------------------
# Project specific values
#--------------------------------------------------------------------
api:
  selector: ecommerce-api

ui:
  selector: ecommerce-ui

worker:
  selector: ecommerce-worker

rabbitmq:
  selector: rabbitmq

#--------------------------------------------------------------------
# Deployment specific values
#--------------------------------------------------------------------
deployments:

  #--------------------------------------------------------------------
  # Api
  #--------------------------------------------------------------------
  api:
    name: ecommerce-api-deployment
    container:
      name: ecommerce-api
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
    image:
      repository: smithhe95/ecommerce-api
      tag: latest
    pullPolicy: Always
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
    environment:
      UiUrl: "https://ecommerce.codesmithing.io"
      ApiUrl: "https://ecommerce-api.codesmithing.io"

  #--------------------------------------------------------------------
  # UI
  #--------------------------------------------------------------------
  ui:
    name: ecommerce-ui-deployment
    container:
      name: ecommerce-ui
      ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
    image:
      repository: smithhe95/ecommerce-ui
      tag: latest
    pullPolicy: Always
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"

  #--------------------------------------------------------------------
  # Worker
  #--------------------------------------------------------------------
  worker:
    name: ecommerce-worker-deployment
    container:
      name: ecommerce-worker
    image:
      repository: smithhe95/ecommerce-worker
      tag: latest
    pullPolicy: Always
    ports:
        - port: 15672
          protocol: TCP
        - port: 5672
          protocol: TCP
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"

  #--------------------------------------------------------------------
  # RabbitMQ
  #--------------------------------------------------------------------
  rabbitmq:
    name: rabbitmq-deployment
    container:
      name: rabbitmq
      image: 
        name: rabbitmq
        tag: 3-management
    pullPolicy: Always
    resources:
      limits:
        cpu: "250m"
        memory: "256Mi"



#--------------------------------------------------------------------
# Service specific values
#--------------------------------------------------------------------
services:

  #--------------------------------------------------------------------
  # Api
  #--------------------------------------------------------------------
  api:
    name: ecommerce-api-service
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
      - port: 443
        targetPort: 443
        protocol: TCP
  
  #--------------------------------------------------------------------
  # UI
  #--------------------------------------------------------------------
  ui:
    name: ecommerce-ui-service
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
      - port: 443
        targetPort: 443
        protocol: TCP

  #--------------------------------------------------------------------
  # RabbitMQ
  #--------------------------------------------------------------------
  rabbitmq:
    name: ecommerce-rabbitmq-service
    type: ClusterIP
    ports:
      - port: 15672
        targetPort: 15672
        protocol: TCP
      - port: 5672
        targetPort: 5672
        protocol: TCP



#--------------------------------------------------------------------
# HPA specific values
#--------------------------------------------------------------------
autoscalers:

  #--------------------------------------------------------------------
  # Api
  #--------------------------------------------------------------------
  api:
    name: ecommerce-api-hpa
    replicas:
      min: 1
      max: 3
    averageUtilization: 80

  #--------------------------------------------------------------------
  # UI
  #--------------------------------------------------------------------
  ui:
    name: ecommerce-ui-hpa
    replicas:
      min: 1
      max: 2
    averageUtilization: 80
  
  #--------------------------------------------------------------------
  # Worker
  #--------------------------------------------------------------------
  worker:
    name: ecommerce-worker-hpa
    replicas:
      min: 1
      max: 2
    averageUtilization: 80



#--------------------------------------------------------------------
# Ingress specific values
#--------------------------------------------------------------------
ingress:
  enabled: true
  name: ecommerce-ingress
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: "{{ .Values.tls.uiSecret }}"
      hosts:
        - ecommerce.codesmithing.io
  hosts:
    - host: ecommerce-api.codesmithing.io
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: "{{ .Values.services.api.name }}"
            port: 80
    - host: ecommerce.codesmithing.io
      paths:
        - path: /
          pathType: Prefix
          service:
            name: "{{ .Values.services.ui.name }}"
            port: 80