### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  commentId: N:Ecommerce.Application.Features.Order.Commands.DeleteOrder
  id: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  children:
  - Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  - Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommandHandler
  langs:
  - csharp
  - vb
  name: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  nameWithType: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  type: Namespace
  assemblies:
  - Ecommerce.Application
references:
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  commentId: T:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  parent: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.html
  name: DeleteOrderCommand
  nameWithType: DeleteOrderCommand
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommandHandler
  commentId: T:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommandHandler
  href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommandHandler.html
  name: DeleteOrderCommandHandler
  nameWithType: DeleteOrderCommandHandler
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommandHandler
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  commentId: N:Ecommerce.Application.Features.Order.Commands.DeleteOrder
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  nameWithType: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Order
    name: Order
    href: Ecommerce.Application.Features.Order.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands
    name: Commands
    href: Ecommerce.Application.Features.Order.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
    name: DeleteOrder
    href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Order
    name: Order
    href: Ecommerce.Application.Features.Order.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands
    name: Commands
    href: Ecommerce.Application.Features.Order.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
    name: DeleteOrder
    href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.html
