### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  commentId: T:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  id: DeleteOrderCommand
  parent: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  children:
  - Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor
  - Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
  langs:
  - csharp
  - vb
  name: DeleteOrderCommand
  nameWithType: DeleteOrderCommand
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  type: Class
  source:
    remote:
      path: Core/Ecommerce.Application/Features/Order/Commands/DeleteOrder/DeleteOrderCommand.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: DeleteOrderCommand
    path: ../../Core/Ecommerce.Application/Features/Order/Commands/DeleteOrder/DeleteOrderCommand.cs
    startLine: 9
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  summary: A <xref href="MediatR.Mediator" data-throw-if-not-resolved="false"></xref> request for deleting an Ecommerce Order
  example: []
  syntax:
    content: 'public class DeleteOrderCommand : IRequest<DeleteOrderResponse>, IBaseRequest'
    content.vb: Public Class DeleteOrderCommand Implements IRequest(Of DeleteOrderResponse), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Ecommerce.Shared.Responses.Order.DeleteOrderResponse}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
  commentId: P:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
  id: Order
  parent: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  langs:
  - csharp
  - vb
  name: Order
  nameWithType: DeleteOrderCommand.Order
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
  type: Property
  source:
    remote:
      path: Core/Ecommerce.Application/Features/Order/Commands/DeleteOrder/DeleteOrderCommand.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: Order
    path: ../../Core/Ecommerce.Application/Features/Order/Commands/DeleteOrder/DeleteOrderCommand.cs
    startLine: 14
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  summary: The Order to be deleted
  example: []
  syntax:
    content: public OrderDto? Order { get; set; }
    parameters: []
    return:
      type: Ecommerce.Shared.Dtos.OrderDto
    content.vb: Public Property Order As OrderDto
  overload: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order*
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor
  commentId: M:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor
  id: '#ctor'
  parent: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand
  langs:
  - csharp
  - vb
  name: DeleteOrderCommand()
  nameWithType: DeleteOrderCommand.DeleteOrderCommand()
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.DeleteOrderCommand()
  type: Constructor
  source:
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Application/Features/Order/Commands/DeleteOrder/DeleteOrderCommand.cs
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  syntax:
    content: public DeleteOrderCommand()
    content.vb: Public Sub New()
  overload: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor*
  nameWithType.vb: DeleteOrderCommand.New()
  fullName.vb: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.New()
  name.vb: New()
references:
- uid: MediatR.Mediator
  commentId: T:MediatR.Mediator
  isExternal: true
  name: Mediator
  nameWithType: Mediator
  fullName: MediatR.Mediator
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  commentId: N:Ecommerce.Application.Features.Order.Commands.DeleteOrder
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  nameWithType: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Order
    name: Order
    href: Ecommerce.Application.Features.Order.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands
    name: Commands
    href: Ecommerce.Application.Features.Order.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
    name: DeleteOrder
    href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Order
    name: Order
    href: Ecommerce.Application.Features.Order.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands
    name: Commands
    href: Ecommerce.Application.Features.Order.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder
    name: DeleteOrder
    href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Ecommerce.Shared.Responses.Order.DeleteOrderResponse}
  commentId: T:MediatR.IRequest{Ecommerce.Shared.Responses.Order.DeleteOrderResponse}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Order/DeleteOrderResponse.cs
  name: IRequest<DeleteOrderResponse>
  nameWithType: IRequest<DeleteOrderResponse>
  fullName: MediatR.IRequest<Ecommerce.Shared.Responses.Order.DeleteOrderResponse>
  nameWithType.vb: IRequest(Of DeleteOrderResponse)
  fullName.vb: MediatR.IRequest(Of Ecommerce.Shared.Responses.Order.DeleteOrderResponse)
  name.vb: IRequest(Of DeleteOrderResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Ecommerce.Shared.Responses.Order.DeleteOrderResponse
    name: DeleteOrderResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Order/DeleteOrderResponse.cs
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Ecommerce.Shared.Responses.Order.DeleteOrderResponse
    name: DeleteOrderResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Order/DeleteOrderResponse.cs
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order*
  commentId: Overload:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
  href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.html#Ecommerce_Application_Features_Order_Commands_DeleteOrder_DeleteOrderCommand_Order
  name: Order
  nameWithType: DeleteOrderCommand.Order
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.Order
- uid: Ecommerce.Shared.Dtos.OrderDto
  commentId: T:Ecommerce.Shared.Dtos.OrderDto
  parent: Ecommerce.Shared.Dtos
  href: Ecommerce.Shared.Dtos.OrderDto.html
  name: OrderDto
  nameWithType: OrderDto
  fullName: Ecommerce.Shared.Dtos.OrderDto
- uid: Ecommerce.Shared.Dtos
  commentId: N:Ecommerce.Shared.Dtos
  href: Ecommerce.html
  name: Ecommerce.Shared.Dtos
  nameWithType: Ecommerce.Shared.Dtos
  fullName: Ecommerce.Shared.Dtos
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Shared
    name: Shared
    href: Ecommerce.Shared.html
  - name: .
  - uid: Ecommerce.Shared.Dtos
    name: Dtos
    href: Ecommerce.Shared.Dtos.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Shared
    name: Shared
    href: Ecommerce.Shared.html
  - name: .
  - uid: Ecommerce.Shared.Dtos
    name: Dtos
    href: Ecommerce.Shared.Dtos.html
- uid: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor*
  commentId: Overload:Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.#ctor
  isExternal: true
  href: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.html#Ecommerce_Application_Features_Order_Commands_DeleteOrder_DeleteOrderCommand__ctor
  name: DeleteOrderCommand
  nameWithType: DeleteOrderCommand.DeleteOrderCommand
  fullName: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.DeleteOrderCommand
  nameWithType.vb: DeleteOrderCommand.New
  fullName.vb: Ecommerce.Application.Features.Order.Commands.DeleteOrder.DeleteOrderCommand.New
  name.vb: New
