### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand
  commentId: T:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand
  id: CreatePayPalReturnKeyCommand
  parent: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  children:
  - Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor
  - Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
  langs:
  - csharp
  - vb
  name: CreatePayPalReturnKeyCommand
  nameWithType: CreatePayPalReturnKeyCommand
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand
  type: Class
  source:
    remote:
      path: Core/Ecommerce.Application/Features/PayPal/Commands/CreatePayPalReturnKey/CreatePayPalReturnKeyCommand.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: CreatePayPalReturnKeyCommand
    path: ../../Core/Ecommerce.Application/Features/PayPal/Commands/CreatePayPalReturnKey/CreatePayPalReturnKeyCommand.cs
    startLine: 7
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  summary: A <xref href="MediatR.Mediator" data-throw-if-not-resolved="false"></xref> request for creating a return key for a PayPal order
  example: []
  syntax:
    content: 'public class CreatePayPalReturnKeyCommand : IRequest<string?>, IBaseRequest'
    content.vb: Public Class CreatePayPalReturnKeyCommand Implements IRequest(Of String), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{System.String}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
  commentId: P:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
  id: OrderId
  parent: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand
  langs:
  - csharp
  - vb
  name: OrderId
  nameWithType: CreatePayPalReturnKeyCommand.OrderId
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
  type: Property
  source:
    remote:
      path: Core/Ecommerce.Application/Features/PayPal/Commands/CreatePayPalReturnKey/CreatePayPalReturnKeyCommand.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: OrderId
    path: ../../Core/Ecommerce.Application/Features/PayPal/Commands/CreatePayPalReturnKey/CreatePayPalReturnKeyCommand.cs
    startLine: 12
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  summary: The Id of the Order to create the return key for
  example: []
  syntax:
    content: public int OrderId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property OrderId As Integer
  overload: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId*
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor
  commentId: M:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor
  id: '#ctor'
  parent: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand
  langs:
  - csharp
  - vb
  name: CreatePayPalReturnKeyCommand()
  nameWithType: CreatePayPalReturnKeyCommand.CreatePayPalReturnKeyCommand()
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.CreatePayPalReturnKeyCommand()
  type: Constructor
  source:
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Application/Features/PayPal/Commands/CreatePayPalReturnKey/CreatePayPalReturnKeyCommand.cs
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  syntax:
    content: public CreatePayPalReturnKeyCommand()
    content.vb: Public Sub New()
  overload: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor*
  nameWithType.vb: CreatePayPalReturnKeyCommand.New()
  fullName.vb: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.New()
  name.vb: New()
references:
- uid: MediatR.Mediator
  commentId: T:MediatR.Mediator
  isExternal: true
  name: Mediator
  nameWithType: Mediator
  fullName: MediatR.Mediator
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  commentId: N:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  href: Ecommerce.html
  name: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  nameWithType: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal
    name: PayPal
    href: Ecommerce.Application.Features.PayPal.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal.Commands
    name: Commands
    href: Ecommerce.Application.Features.PayPal.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
    name: CreatePayPalReturnKey
    href: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal
    name: PayPal
    href: Ecommerce.Application.Features.PayPal.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal.Commands
    name: Commands
    href: Ecommerce.Application.Features.PayPal.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey
    name: CreatePayPalReturnKey
    href: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{System.String}
  commentId: T:MediatR.IRequest{System.String}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: IRequest<string>
  nameWithType: IRequest<string>
  fullName: MediatR.IRequest<string>
  nameWithType.vb: IRequest(Of String)
  fullName.vb: MediatR.IRequest(Of String)
  name.vb: IRequest(Of String)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId*
  commentId: Overload:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
  href: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.html#Ecommerce_Application_Features_PayPal_Commands_CreatePayPalReturnKey_CreatePayPalReturnKeyCommand_OrderId
  name: OrderId
  nameWithType: CreatePayPalReturnKeyCommand.OrderId
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.OrderId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor*
  commentId: Overload:Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.#ctor
  isExternal: true
  href: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.html#Ecommerce_Application_Features_PayPal_Commands_CreatePayPalReturnKey_CreatePayPalReturnKeyCommand__ctor
  name: CreatePayPalReturnKeyCommand
  nameWithType: CreatePayPalReturnKeyCommand.CreatePayPalReturnKeyCommand
  fullName: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.CreatePayPalReturnKeyCommand
  nameWithType.vb: CreatePayPalReturnKeyCommand.New
  fullName.vb: Ecommerce.Application.Features.PayPal.Commands.CreatePayPalReturnKey.CreatePayPalReturnKeyCommand.New
  name.vb: New
