### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  commentId: N:Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  id: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  children:
  - Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommand
  - Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommandHandler
  langs:
  - csharp
  - vb
  name: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  nameWithType: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  fullName: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  type: Namespace
  assemblies:
  - Ecommerce.Application
references:
- uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommand
  commentId: T:Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommand
  parent: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  href: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommand.html
  name: UpdatePasswordCommand
  nameWithType: UpdatePasswordCommand
  fullName: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommand
- uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommandHandler
  commentId: T:Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommandHandler
  href: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommandHandler.html
  name: UpdatePasswordCommandHandler
  nameWithType: UpdatePasswordCommandHandler
  fullName: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.UpdatePasswordCommandHandler
- uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  commentId: N:Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  href: Ecommerce.html
  name: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  nameWithType: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  fullName: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser
    name: EcommerceUser
    href: Ecommerce.Application.Features.EcommerceUser.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser.Commands
    name: Commands
    href: Ecommerce.Application.Features.EcommerceUser.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
    name: UpdatePassword
    href: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser
    name: EcommerceUser
    href: Ecommerce.Application.Features.EcommerceUser.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser.Commands
    name: Commands
    href: Ecommerce.Application.Features.EcommerceUser.Commands.html
  - name: .
  - uid: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword
    name: UpdatePassword
    href: Ecommerce.Application.Features.EcommerceUser.Commands.UpdatePassword.html
