### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery
  commentId: T:Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery
  id: GetAllCategoriesQuery
  parent: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  children:
  - Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor
  langs:
  - csharp
  - vb
  name: GetAllCategoriesQuery
  nameWithType: GetAllCategoriesQuery
  fullName: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery
  type: Class
  source:
    remote:
      path: Core/Ecommerce.Application/Features/Category/Queries/GetAllCategories/GetAllCategoriesQuery.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: GetAllCategoriesQuery
    path: ../../Core/Ecommerce.Application/Features/Category/Queries/GetAllCategories/GetAllCategoriesQuery.cs
    startLine: 8
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  summary: A <xref href="MediatR.Mediator" data-throw-if-not-resolved="false"></xref> request for retrieving all existing <xref href="Ecommerce.Application.Features.Category" data-throw-if-not-resolved="false"></xref> entities
  example: []
  syntax:
    content: 'public class GetAllCategoriesQuery : IRequest<GetAllCategoriesResponse>, IBaseRequest'
    content.vb: Public Class GetAllCategoriesQuery Implements IRequest(Of GetAllCategoriesResponse), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor
  commentId: M:Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor
  id: '#ctor'
  parent: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery
  langs:
  - csharp
  - vb
  name: GetAllCategoriesQuery()
  nameWithType: GetAllCategoriesQuery.GetAllCategoriesQuery()
  fullName: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.GetAllCategoriesQuery()
  type: Constructor
  source:
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Application/Features/Category/Queries/GetAllCategories/GetAllCategoriesQuery.cs
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  syntax:
    content: public GetAllCategoriesQuery()
    content.vb: Public Sub New()
  overload: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor*
  nameWithType.vb: GetAllCategoriesQuery.New()
  fullName.vb: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.New()
  name.vb: New()
references:
- uid: MediatR.Mediator
  commentId: T:MediatR.Mediator
  isExternal: true
  name: Mediator
  nameWithType: Mediator
  fullName: MediatR.Mediator
- uid: Ecommerce.Application.Features.Category
  commentId: N:Ecommerce.Application.Features.Category
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Category
  nameWithType: Ecommerce.Application.Features.Category
  fullName: Ecommerce.Application.Features.Category
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
- uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  commentId: N:Ecommerce.Application.Features.Category.Queries.GetAllCategories
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  nameWithType: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  fullName: Ecommerce.Application.Features.Category.Queries.GetAllCategories
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries
    name: Queries
    href: Ecommerce.Application.Features.Category.Queries.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories
    name: GetAllCategories
    href: Ecommerce.Application.Features.Category.Queries.GetAllCategories.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries
    name: Queries
    href: Ecommerce.Application.Features.Category.Queries.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories
    name: GetAllCategories
    href: Ecommerce.Application.Features.Category.Queries.GetAllCategories.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse}
  commentId: T:MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetAllCategoriesResponse.cs
  name: IRequest<GetAllCategoriesResponse>
  nameWithType: IRequest<GetAllCategoriesResponse>
  fullName: MediatR.IRequest<Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse>
  nameWithType.vb: IRequest(Of GetAllCategoriesResponse)
  fullName.vb: MediatR.IRequest(Of Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse)
  name.vb: IRequest(Of GetAllCategoriesResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse
    name: GetAllCategoriesResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetAllCategoriesResponse.cs
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Ecommerce.Shared.Responses.Category.GetAllCategoriesResponse
    name: GetAllCategoriesResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetAllCategoriesResponse.cs
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor*
  commentId: Overload:Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.#ctor
  isExternal: true
  href: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.html#Ecommerce_Application_Features_Category_Queries_GetAllCategories_GetAllCategoriesQuery__ctor
  name: GetAllCategoriesQuery
  nameWithType: GetAllCategoriesQuery.GetAllCategoriesQuery
  fullName: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.GetAllCategoriesQuery
  nameWithType.vb: GetAllCategoriesQuery.New
  fullName.vb: Ecommerce.Application.Features.Category.Queries.GetAllCategories.GetAllCategoriesQuery.New
  name.vb: New
