### YamlMime:ManagedReference
items:
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery
  commentId: T:Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery
  id: GetCategoryByIdQuery
  parent: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  children:
  - Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor
  - Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
  langs:
  - csharp
  - vb
  name: GetCategoryByIdQuery
  nameWithType: GetCategoryByIdQuery
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery
  type: Class
  source:
    remote:
      path: Core/Ecommerce.Application/Features/Category/Queries/GetCategoryById/GetCategoryByIdQuery.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: GetCategoryByIdQuery
    path: ../../Core/Ecommerce.Application/Features/Category/Queries/GetCategoryById/GetCategoryByIdQuery.cs
    startLine: 8
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  summary: A <xref href="MediatR.Mediator" data-throw-if-not-resolved="false"></xref> request for retrieving an existing <xref href="Ecommerce.Application.Features.Category" data-throw-if-not-resolved="false"></xref> by its Id
  example: []
  syntax:
    content: 'public class GetCategoryByIdQuery : IRequest<GetCategoryByIdResponse>, IBaseRequest'
    content.vb: Public Class GetCategoryByIdQuery Implements IRequest(Of GetCategoryByIdResponse), IBaseRequest
  inheritance:
  - System.Object
  implements:
  - MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse}
  - MediatR.IBaseRequest
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
  commentId: P:Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
  id: Id
  parent: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: GetCategoryByIdQuery.Id
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
  type: Property
  source:
    remote:
      path: Core/Ecommerce.Application/Features/Category/Queries/GetCategoryById/GetCategoryByIdQuery.cs
      branch: dev
      repo: https://github.com/smithhe/EcommerceApp.git
    id: Id
    path: ../../Core/Ecommerce.Application/Features/Category/Queries/GetCategoryById/GetCategoryByIdQuery.cs
    startLine: 13
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  summary: The unique identifier of the <xref href="Ecommerce.Application.Features.Category" data-throw-if-not-resolved="false"></xref> to retrieve
  example: []
  syntax:
    content: public int Id { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Id As Integer
  overload: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id*
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor
  commentId: M:Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor
  id: '#ctor'
  parent: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery
  langs:
  - csharp
  - vb
  name: GetCategoryByIdQuery()
  nameWithType: GetCategoryByIdQuery.GetCategoryByIdQuery()
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.GetCategoryByIdQuery()
  type: Constructor
  source:
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Application/Features/Category/Queries/GetCategoryById/GetCategoryByIdQuery.cs
  assemblies:
  - Ecommerce.Application
  namespace: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  syntax:
    content: public GetCategoryByIdQuery()
    content.vb: Public Sub New()
  overload: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor*
  nameWithType.vb: GetCategoryByIdQuery.New()
  fullName.vb: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.New()
  name.vb: New()
references:
- uid: MediatR.Mediator
  commentId: T:MediatR.Mediator
  isExternal: true
  name: Mediator
  nameWithType: Mediator
  fullName: MediatR.Mediator
- uid: Ecommerce.Application.Features.Category
  commentId: N:Ecommerce.Application.Features.Category
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Category
  nameWithType: Ecommerce.Application.Features.Category
  fullName: Ecommerce.Application.Features.Category
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  commentId: N:Ecommerce.Application.Features.Category.Queries.GetCategoryById
  href: Ecommerce.html
  name: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  nameWithType: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById
  spec.csharp:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries
    name: Queries
    href: Ecommerce.Application.Features.Category.Queries.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById
    name: GetCategoryById
    href: Ecommerce.Application.Features.Category.Queries.GetCategoryById.html
  spec.vb:
  - uid: Ecommerce
    name: Ecommerce
    href: Ecommerce.html
  - name: .
  - uid: Ecommerce.Application
    name: Application
    href: Ecommerce.Application.html
  - name: .
  - uid: Ecommerce.Application.Features
    name: Features
    href: Ecommerce.Application.Features.html
  - name: .
  - uid: Ecommerce.Application.Features.Category
    name: Category
    href: Ecommerce.Application.Features.Category.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries
    name: Queries
    href: Ecommerce.Application.Features.Category.Queries.html
  - name: .
  - uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById
    name: GetCategoryById
    href: Ecommerce.Application.Features.Category.Queries.GetCategoryById.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse}
  commentId: T:MediatR.IRequest{Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse}
  parent: MediatR
  definition: MediatR.IRequest`1
  href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetCategoryByIdResponse.cs
  name: IRequest<GetCategoryByIdResponse>
  nameWithType: IRequest<GetCategoryByIdResponse>
  fullName: MediatR.IRequest<Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse>
  nameWithType.vb: IRequest(Of GetCategoryByIdResponse)
  fullName.vb: MediatR.IRequest(Of Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse)
  name.vb: IRequest(Of GetCategoryByIdResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - uid: Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse
    name: GetCategoryByIdResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetCategoryByIdResponse.cs
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: Ecommerce.Shared.Responses.Category.GetCategoryByIdResponse
    name: GetCategoryByIdResponse
    href: https://github.com/smithhe/EcommerceApp/blob/2d02db4bfed44ad43113812b0f7c0bdb0781183e/Core/Ecommerce.Shared/Responses/Category/GetCategoryByIdResponse.cs
  - name: )
- uid: MediatR.IBaseRequest
  commentId: T:MediatR.IBaseRequest
  parent: MediatR
  isExternal: true
  name: IBaseRequest
  nameWithType: IBaseRequest
  fullName: MediatR.IBaseRequest
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MediatR.IRequest`1
  commentId: T:MediatR.IRequest`1
  isExternal: true
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: MediatR.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: MediatR.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: MediatR.IRequest`1
    name: IRequest
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: MediatR
  commentId: N:MediatR
  isExternal: true
  name: MediatR
  nameWithType: MediatR
  fullName: MediatR
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id*
  commentId: Overload:Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
  href: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.html#Ecommerce_Application_Features_Category_Queries_GetCategoryById_GetCategoryByIdQuery_Id
  name: Id
  nameWithType: GetCategoryByIdQuery.Id
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.Id
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor*
  commentId: Overload:Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.#ctor
  isExternal: true
  href: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.html#Ecommerce_Application_Features_Category_Queries_GetCategoryById_GetCategoryByIdQuery__ctor
  name: GetCategoryByIdQuery
  nameWithType: GetCategoryByIdQuery.GetCategoryByIdQuery
  fullName: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.GetCategoryByIdQuery
  nameWithType.vb: GetCategoryByIdQuery.New
  fullName.vb: Ecommerce.Application.Features.Category.Queries.GetCategoryById.GetCategoryByIdQuery.New
  name.vb: New
