name: Merge Into Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get the sources
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: smithhe95
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      - name: Build and Push Api Image
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake
          arguments: |
            build: API
            configuration: Release
            target: Docker Push
            dockerWorkingDirectory: ${{ github.workspace }}
      
      - name: Build and Push UI Image
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake
          arguments: |
            build: UI
            configuration: Release
            target: Docker Push
            environmentArg: ${{ vars.UI_ENVIRONMENT }}
            dockerWorkingDirectory: ${{ github.workspace }}
