name: 'Merge Into Dev'

# Trigger the action on push to dev
on:
  push:
    branches: [ "dev" ]

jobs:
  Build-And-Push-Api-Image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the source
      - name: Get the sources
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: smithhe95
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      # Step 3: Build and Push the API Image
      - name: Build and Push Api Image
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake
          arguments: |
            build: API
            configuration: Release
            target: Docker Push
            dockerWorkingDirectory: ${{ github.workspace }}
  
  Build-And-Push-UI-Image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the source
      - name: Get the sources
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: smithhe95
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      # Step 3: Build and Push the UI Image
      - name: Build and Push UI Image
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake
          arguments: |
            build: UI
            configuration: Release
            target: Docker Push
            environmentArg: ${{ vars.UI_ENVIRONMENT }}
            dockerWorkingDirectory: ${{ github.workspace }}
  
  Build-And-Push-Worker-Image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the source
      - name: Get the sources
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: smithhe95
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}

      # Step 3: Build and Push the Worker Image
      - name: Build and Push Worker Image
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake
          arguments: |
            build: Worker
            configuration: Release
            target: Docker Push
            dockerWorkingDirectory: ${{ github.workspace }}
