name: 'PR Build And Test'

# Trigger the action on any pull request
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Get the source
      - name: Get the sources
        uses: actions/checkout@v4

      # Step 2: Setup CakeBuild
      - name: Setup Cake
        run: |
          dotnet tool install Cake.Tool --version 5.0.0

      # Step 3: Run the cake build script
      - name: Run the build script
        run: |
          dotnet cake ./BuildFiles/build.cake