name: PR Build And Test

on:
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the sources
        uses: actions/checkout@v3
      - name: Run the build script
        uses: cake-build/cake-action@v2
        with:
          cake-version: 4.0.0
          script-path: ./BuildFiles/build.cake